# Generated by Django 5.0.6 on 2024-07-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Pagamenti'},
        ),
    ]
