"""
Django settings for tenniscoach project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oo-eu8*3%0*f=ybnu^z76vhkyr9y4whd^zi4zspb#+%o2w4ngv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    "essential",
    "users",
    'payments',
    'custom_payment'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tenniscoach.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tenniscoach.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# Imposta la lingua di default su Italiano
LANGUAGE_CODE = 'it'

# Aggiungi i linguaggi supportati
LANGUAGES = [
    ('it', 'Italiano'),
    ('en', 'English'),
]

# Configura la timezone
TIME_ZONE = 'Europe/Rome'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


STATIC_URL = 'media/static/'
STATICFILES_DIRS = [os.path.join(MEDIA_ROOT, 'static/')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = "/?login=ok" #redireziona alla home, ma con un parametro GET
LOGIN_URL = "/login/?auth=notok" #redireziona al login, ma con un parametro GET

PAYMENT_VARIANTS = {
    'stripe': ('payments.stripe.StripeProvider', {
        'secret_key': 'sk_test_51PUn1dRvj7DKfmazvogNOjjd9w5GrB1WTmZfsuSWVOfHUfY4MPOZvXIXpgxZW2lAB3xP3zda6uC0bNo6v92BoV8300k7YPBrBU',
        'public_key': 'pk_test_51PUn1dRvj7DKfmazYUL00PT9Q9FPPpExtVaZq1Noz4O3Couuy2aKZvnTFqpExZX7G7h4aiKvyr5FZ2Uu58mgxDdQ009MLCo3rX',
    }),
}

# Configurazione per usare carte di prova
STRIPE_TEST_PUBLIC_KEY = 'pk_test_51PUn1dRvj7DKfmazYUL00PT9Q9FPPpExtVaZq1Noz4O3Couuy2aKZvnTFqpExZX7G7h4aiKvyr5FZ2Uu58mgxDdQ009MLCo3rX'
STRIPE_TEST_SECRET_KEY = 'sk_test_51PUn1dRvj7DKfmazvogNOjjd9w5GrB1WTmZfsuSWVOfHUfY4MPOZvXIXpgxZW2lAB3xP3zda6uC0bNo6v92BoV8300k7YPBrBU'

PAYMENT_HOST = 'localhost'  # Sostituisci con il tuo dominio in produzione
PAYMENT_USES_SSL = False  # Imposta su True in produzione con HTTPS
SITE_ID = 1  # Assicurati che il SITE_ID sia impostato
PAYMENT_MODEL = 'custom_payment.Payment'  # Usa il modello di pagamento predefinito di django-payments
