# Generated by Django 5.0.6 on 2024-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='images\\unknown_user.jpg', upload_to='users_pics'),
        ),
    ]
