# Generated by Django 5.0.6 on 2024-06-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0013_alter_course_picture_alter_purchase_utente'),
        ('users', '0003_profile_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='purchases',
            field=models.ManyToManyField(blank=True, related_name='profile_purchases', through='essential.Purchase', to='essential.course'),
        ),
    ]
