# Generated by Django 5.0.6 on 2024-07-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profili utente'},
        ),
    ]
