# Generated by Django 5.0.6 on 2024-06-15 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0004_profile_email_alter_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='static/images\\unknown_course.png', upload_to='courses_pics'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='videos',
            field=models.FileField(blank=True, default='static/videos\\unknown_video.mp4', upload_to='courses_videos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='static/images\\unknown_user.webp', upload_to='users_pics'),
        ),
    ]
