# Generated by Django 5.0.6 on 2024-06-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0005_course_date_alter_course_picture_alter_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='principiante', max_length=20),
            preserve_default=False,
        ),
    ]
