# Generated by Django 5.0.6 on 2024-06-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0006_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='static/images\\unknown_course1.jpg', upload_to='courses_pics'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
