# Generated by Django 5.0.6 on 2024-06-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0008_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
