# Generated by Django 5.0.6 on 2024-06-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0009_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='videos',
            field=models.FileField(blank=True, default='courses_videos\\unknown_video.mp4', upload_to='courses_videos/'),
        ),
    ]
