# Generated by Django 5.0.6 on 2024-06-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0010_alter_lesson_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='images\\unknown_course1.jpg', upload_to='courses_pics'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='videos',
            field=models.FileField(blank=True, default='static/videos\\unknown_video.mp4', upload_to='courses_videos/'),
        ),
    ]
