# Generated by Django 5.0.6 on 2024-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0011_alter_course_picture_alter_lesson_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='videos',
            field=models.FileField(blank=True, default='videos\\unknown_video.mp4', upload_to='courses_videos/'),
        ),
    ]
