# Generated by Django 5.0.6 on 2024-06-23 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0012_alter_lesson_videos'),
        ('users', '0002_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='images\\unknown_course1.jpg', upload_to='courses_pics/'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.profile'),
        ),
    ]
