# Generated by Django 5.0.6 on 2024-06-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0013_alter_course_picture_alter_purchase_utente'),
        ('users', '0004_alter_profile_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='corso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essential.course'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
