# Generated by Django 5.0.6 on 2024-06-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0014_alter_lesson_duration_alter_purchase_corso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='images\\unknown_course1.jpg', upload_to='static/courses_pics/'),
        ),
    ]
