# Generated by Django 5.0.6 on 2024-06-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0015_alter_course_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='images\\unknown_course1.jpg', upload_to='courses_pics/'),
        ),
    ]
