# Generated by Django 5.0.6 on 2024-06-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0019_alter_course_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(blank=True),
        ),
    ]
