# Generated by Django 5.0.6 on 2024-07-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0022_alter_purchase_options_rename_videos_lesson_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'Acquisti'},
        ),
        migrations.AddField(
            model_name='course',
            name='purchases_number',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
