# Generated by Django 5.0.6 on 2024-07-06 08:27

import essential.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0023_alter_purchase_options_course_purchases_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, default='videos\\unknown_video.mp4', upload_to='courses_videos/', validators=[essential.models.validate_mp4_file]),
        ),
    ]
